# Generated by Django 3.0.5 on 2021-04-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(blank=True, null=True)),
                ('session', models.URLField(blank=True, max_length=300, null=True)),
                ('resource', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
