# Generated by Django 3.0.7 on 2021-04-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0003_auto_20210411_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='cp',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
