# Generated by Django 3.0.7 on 2021-04-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0005_dev'),
    ]

    operations = [
        migrations.CreateModel(
            name='problemofday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_of_the_day', models.URLField(blank=True, max_length=300, null=True)),
                ('old_questions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
