# Generated by Django 3.0.5 on 2021-04-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0006_problemofday'),
    ]

    operations = [
        migrations.CreateModel(
            name='problemset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('date_of_problem', models.DateField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('ratings', models.CharField(default=1200, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='problemofday',
            name='ratings',
            field=models.CharField(default=1200, max_length=100),
        ),
        migrations.AddField(
            model_name='problemofday',
            name='tags',
            field=models.CharField(default='implementation', max_length=200),
        ),
    ]
