# Generated by Django 3.0.5 on 2021-04-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0007_auto_20210415_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
