# Generated by Django 3.0.5 on 2021-04-18 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0008_problemset_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cp',
        ),
        migrations.DeleteModel(
            name='problemofday',
        ),
        migrations.DeleteModel(
            name='problemset',
        ),
    ]
