# Generated by Django 3.0.5 on 2021-04-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0009_auto_20210418_0602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
        migrations.DeleteModel(
            name='display',
        ),
    ]
