# Generated by Django 3.0.5 on 2021-04-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0010_auto_20210418_0618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dev',
        ),
    ]
