# Generated by Django 3.0.5 on 2021-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cse', '0011_delete_dev'),
    ]

    operations = [
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(blank=True, max_length=200, null=True)),
                ('subjects', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('book', models.TextField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
