# Generated by Django 3.2.5 on 2021-07-04 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0013_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='other_stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_down', models.TextField(blank=True, null=True)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cse.subject')),
            ],
        ),
    ]
