# Generated by Django 3.2.5 on 2021-07-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0014_other_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_name',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='other_stuff',
            name='other_name',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
