# Generated by Django 3.2.5 on 2021-07-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0015_auto_20210704_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='sub',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='other_stuff',
            old_name='sub',
            new_name='subject',
        ),
    ]
