# Generated by Django 3.2.5 on 2021-07-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0016_auto_20210705_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='subject',
            new_name='sub',
        ),
        migrations.RenameField(
            model_name='other_stuff',
            old_name='subject',
            new_name='sub',
        ),
    ]
