# Generated by Django 3.2.5 on 2021-07-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0017_auto_20210705_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='sub',
            new_name='subj',
        ),
    ]
