# Generated by Django 3.2.5 on 2021-07-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0018_rename_sub_books_subj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='other_stuff',
            old_name='sub',
            new_name='subj',
        ),
    ]
