# Generated by Django 3.2.5 on 2021-07-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0019_rename_sub_other_stuff_subj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='view_down',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='other_stuff',
            name='view_down',
            field=models.URLField(blank=True, null=True),
        ),
    ]
