# Generated by Django 3.0.5 on 2021-04-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokenStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
