# Generated by Django 3.0.5 on 2021-04-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210422_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenstuff',
            old_name='time',
            new_name='date_time',
        ),
    ]
