# Generated by Django 3.0.5 on 2021-04-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210422_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenstuff',
            name='date_time',
        ),
        migrations.AddField(
            model_name='tokenstuff',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenstuff',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
