# Generated by Django 3.0.5 on 2021-04-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_details_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenstuff',
            name='date',
        ),
        migrations.AddField(
            model_name='tokenstuff',
            name='expires_in',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokenstuff',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
