# Generated by Django 3.2.5 on 2021-07-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
    ]
