# Generated by Django 3.0.5 on 2021-04-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='problemofday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_of_the_day', models.URLField(blank=True, max_length=300, null=True)),
                ('old_questions', models.TextField(blank=True, null=True)),
                ('ratings', models.CharField(default=1200, max_length=100)),
                ('tags', models.CharField(default='implementation', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='problemset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('date_of_problem', models.DateField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('ratings', models.CharField(default=1200, max_length=100)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
