# Generated by Django 3.0.5 on 2021-04-18 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='date_of_problem',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 19, 58, 53, 669926, tzinfo=utc)),
        ),
    ]
