# Generated by Django 3.0.5 on 2021-04-18 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0002_auto_20210418_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='date_of_problem',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 19, 59, 48, 468160)),
        ),
    ]
