# Generated by Django 3.0.5 on 2021-04-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0003_auto_20210418_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='date_of_problem',
            field=models.DateField(blank=True, null=True),
        ),
    ]
